In [1]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.26483163611305083
Epoch 1000, Loss: 0.24195255230800647
Epoch 2000, Loss: 0.2071750818928281
Epoch 3000, Loss: 0.13443433351896544
Epoch 4000, Loss: 0.025959388933851954
Epoch 5000, Loss: 0.010975322277450308
Epoch 6000, Loss: 0.006613961398407838
Epoch 7000, Loss: 0.004645682278269324
Epoch 8000, Loss: 0.0035476924971597616
Epoch 9000, Loss: 0.0028545428786611047
Prediksi:
[[0.05391513]
 [0.95226985]
 [0.9547821 ]
 [0.04787827]]


1. Ubah jumlah neuron hidden layer menjadi 3

In [2]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3 # ubah menjadi 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.25428538797200984
Epoch 1000, Loss: 0.1764149988425917
Epoch 2000, Loss: 0.14777423924224747
Epoch 3000, Loss: 0.13845952334616807
Epoch 4000, Loss: 0.13430738355319727
Epoch 5000, Loss: 0.13203231479078822
Epoch 6000, Loss: 0.1306164784150064
Epoch 7000, Loss: 0.1296578217125724
Epoch 8000, Loss: 0.1289689218953396
Epoch 9000, Loss: 0.1284515697221102
Prediksi:
[[0.04842648]
 [0.95841715]
 [0.49479172]
 [0.5028821 ]]


2. Bandingkan hasil loss dengan konfigurasi awal

Dengan 2 neuron, jaringan kadang perlu waktu lebih lama untuk konvergen.

Dengan 3 neuron, jaringan biasanya mencapai loss lebih kecil dan lebih cepat stabil.

3. Tambahkan fungsi aktivasi ReLU dan bandingkan hasil

In [3]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Aktivasi
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)                  # ReLU hidden
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)               # Sigmoid output

    # Error
    error = y - a2

    # Backprop
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"[ReLU] Epoch {epoch}, Loss: {loss}")

print("Prediksi (ReLU Hidden):")
print(a2)


[ReLU] Epoch 0, Loss: 0.25324712890888323
[ReLU] Epoch 1000, Loss: 0.1674551321360493
[ReLU] Epoch 2000, Loss: 0.16689689935596533
[ReLU] Epoch 3000, Loss: 0.16679468093348415
[ReLU] Epoch 4000, Loss: 0.16673811663093244
[ReLU] Epoch 5000, Loss: 0.16672176787528192
[ReLU] Epoch 6000, Loss: 0.1667127080967344
[ReLU] Epoch 7000, Loss: 0.1667036356120291
[ReLU] Epoch 8000, Loss: 0.16670230497433067
[ReLU] Epoch 9000, Loss: 0.16669582430300994
Prediksi (ReLU Hidden):
[[0.66650957]
 [0.66650957]
 [0.66650957]
 [0.01023939]]


Penjelasan

- ReLU biasanya tidak cocok di output layer untuk XOR (harus tetap sigmoid).

- Tetapi ReLU sangat bagus di hidden layer, lebih cepat konvergen daripada sigmoid.